# Generated by Django 4.1.7 on 2023-06-06 21:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mini_avito_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cp_name', models.CharField(max_length=40, verbose_name='cp_name')),
            ],
            options={
                'db_table': 'category_products',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, validators=[mini_avito_app.models.validation_created_date], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, validators=[mini_avito_app.models.validation_created_date], verbose_name='modified')),
                ('address', models.TextField(blank=True, max_length=40, null=True, verbose_name='address')),
                ('full_name', models.CharField(max_length=40, verbose_name='full_name')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, validators=[mini_avito_app.models.validate_phone_number], verbose_name='phone')),
                ('mail', models.CharField(blank=True, max_length=40, null=True, validators=[mini_avito_app.models.validate_mail], verbose_name='mail')),
                ('image_client', models.ImageField(blank=True, default='clients/default_avatar.png', null=True, upload_to='clients/', verbose_name='image_client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='imgs/')),
            ],
            options={
                'db_table': 'imgs',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, validators=[mini_avito_app.models.validation_created_date], verbose_name='created')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('available', models.BooleanField(verbose_name='available')),
                ('description', models.TextField(verbose_name='description')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[mini_avito_app.models.validate_price], verbose_name='price')),
                ('cur_img', models.ImageField(blank=True, default='products/default_product.png', null=True, upload_to='products/', verbose_name='cur_img')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_avito_app.client')),
                ('p_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_avito_app.category_products')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, validators=[mini_avito_app.models.validation_created_date], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, validators=[mini_avito_app.models.validation_created_date], verbose_name='modified')),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting')], default='Waiting', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[mini_avito_app.models.validate_price], verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Waiting', 'Waiting')], default='Waiting', max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_avito_app.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_avito_app.products')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Images_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_avito_app.images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_avito_app.products')),
            ],
            options={
                'db_table': 'images_products',
            },
        ),
    ]
