# Generated by Django 4.1.7 on 2023-06-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_avito_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Waiting', 'Waiting'), ('Completed', 'Completed')], default='Waiting', max_length=40),
        ),
    ]
