# Generated by Django 4.2 on 2023-06-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_avito_app', '0002_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_products',
            new_name='CategoryProducts',
        ),
        migrations.RenameModel(
            old_name='Images_products',
            new_name='ImagesProducts',
        ),
    ]
