name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r mini_avito/tests/flake_requirements.txt
    - name: Flake8
      run: flake8 .
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 1234
          POSTGRES_DBNAME: postgres
          POSTGRES_USER: admin
          POSTGRES_PORT: 38746
          POSTGRES_HOST: 127.0.0.1
        ports:
          - 38746:5432
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r mini_avito/tests/requirements.txt
      - name: Создание env
        run: |
          echo "PG_PORT=38746" >> mini_avito/.env
          echo "PG_USER=admin" >> mini_avito/.env
          echo "PG_PASSWORD=1234" >> mini_avito/.env
          echo "PG_DBNAME=postgres" >> mini_avito/.env
          echo "PG_HOST=127.0.0.1" >> mini_avito/.env
          echo "SECRET_KEY=test" >> mini_avito/.env
      - name: Тесты
        run: |
          python3 manage.py makemigrations mini_avito_app
          python3 manage.py migrate
          python3 manage.py test tests