name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r first/tests/flake_requirements.txt
    - name: Flake8
      run: flake8 .
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
            POSTGRES_PASSWORD: change_me
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: sirius_2023
            POSTGRES_PORT: 5555
            POSTGRES_HOST: 127.0.0.1
        ports:
          - 5555:5432
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r first/tests/test_requirements.txt
    - name: Тесты bash-curl
      run: |
        chmod +x first/tests/test.sh
        first/tests/test.sh
    - name: Тесты python-requests
      run: |
        pytest first/tests/test_requests.py
  container-job2:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DBNAME: postgres
          POSTGRES_USER: test
          POSTGRES_PORT: 5432
          POSTGRES_HOST: 127.0.0.1
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r second/restaurants/tests/requirements.txt
      - name: Тесты django rest api
        run: |
          chmod +x second/restaurants/tests/test.sh 
          ./second/restaurants/tests/test.sh tests.test_rest